---
- hosts: all
  gather_facts: false
  roles:
    - common_ssh
- hosts: all
  gather_facts: true
  roles:
    - common
    - cronapt
    - telegraf
    - nagios_agent

- hosts: rsnapshot_client
  gather_facts: true
  roles:
    - rsnapshot_client
