---
- hosts: all
  gather_facts: False
  roles:
    - common
    - acme.sh
    - cronapt
    - telegraf
    - nagios_agent

- hosts: all
  roles:
    - common-debian

- hosts: all
  roles:
    - common-ubuntu

#- hosts: rsnapshot_client
#  gather_facts: true
#  roles:
#    - rsnapshot_client

- hosts: jitsisignal
  roles:
    - frontendserver
    - instances

- hosts: videobridge
  roles:
    - videobridge

- hosts: turnserver
  roles:
    - turnserver
