---
- hosts: debian
  roles:
    - common-debian

- hosts: ubuntu
  roles:
    - common_ssh
    - common

- hosts: all
  gather_facts: true
  roles:
    - acme.sh
    - cronapt
#    - telegraf
#    - nagios_agent

#- hosts: rsnapshot_client
#  gather_facts: true
#  roles:
#    - rsnapshot_client

- hosts: jitsisignal
  roles:
    - frontendserver

#- hosts: jitsisignal
#  roles:
#    - instances

- hosts: jitsivideobride
  roles:
    - videobridge

- hosts: turnserver
  roles:
    - turnserver
