---
- hosts: debian
  roles:
    - common-debian
  gather_facts: true
  pre_tasks:
    - setup:
        filter: "ansible_distribution == 'Debian'"

- hosts: debian
  roles:
    - common_ssh
    - common
  gather_facts: true
  pre_tasks:
    - setup:
        filter: "ansible_distribution == 'Ubuntu'"

- hosts: all
  gather_facts: true
  roles:
#    - acme.sh
    - common
    - cronapt
#    - telegraf
#    - nagios_agent

#- hosts: rsnapshot_client
#  gather_facts: true
#  roles:
#    - rsnapshot_client

- hosts: jitsi
  roles:
    - jitsicommon

- hosts: jitsisignal
  roles:
    - frontendserver

- hosts: jitsisignal
  roles:
    - instances

- hosts: jitsivideobride
  roles:
    - videobridge

- hosts: turnserver
  roles:
    - turnserver
