---
- name: Install Jitsi Repo signing key
  apt_key:
    url: https://download.jitsi.org/jitsi-key.gpg.key 
    state: present

- name: Add Repo for jitsi
  apt_repository:
    repo: "deb http://download.jitsi.org stable/"
    filename: jitsi
    state: present

- name: Update package cache
  apt:
    autoclean: yes
    cache_valid_time: 0
    update_cache: yes

- name: Set debconf-answers for jitsi-meet
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  loop:
    - { name: 'jitsi-videobridge', question: 'jitsi-videobridge/jvb-hostname', value: '{{ hostname }}', vtype: 'string' }

- name: install stuff
  apt:
    name:
      - default-jre-headless
      - jitsi-videobridge2

- name: generate /etc/jitsi/videobridge/logging.properties
  template:
    src: logging.properties.j2
    dest: /etc/jitsi/videobridge/logging.properties
    owner: jvb
    group: jitsi
    mode: "0644"
    backup: yes
  notify:
    - restart videobridge

- name: generate /etc/jitsi/videobridge/config
  template:
    src: config.j2
    dest: /etc/jitsi/videobridge/config
    owner: jvb
    group: jitsi
    mode: "0644"
    backup: yes
  notify:
    - restart videobridge

- name: generate /etc/jitsi/videobridge/jvb.conf
  template:
    src: jvb.conf.j2
    dest: /etc/jitsi/videobridge/jvb.conf
    owner: jvb
    group: jitsi
    mode: "0644"
    backup: yes
  notify:
    - restart videobridge

- name: generate /etc/jitsi/videobridge/sip-communicator.properties
  template:
    src: sip-communicator.properties.j2
    dest: /etc/jitsi/videobridge/sip-communicator.properties
    owner: jvb
    group: jitsi
    mode: "0644"
    backup: yes
  notify:
    - restart videobridge

- name: generate /etc/logrotate.d/jitsi-videobridge
  template:
    src: jitsi-videobridge.j2
    dest: /etc/logrotate.d/jitsi-videobridge
    owner: root
    group: root
    mode: "0644"
    backup: yes
  notify:
    - restart logrotate

- name: generate /etc/sysctl.d/20-jvb-udp-buffers.conf
  template:
    src: 20-jvb-udp-buffers.conf.j2
    dest: /etc/sysctl.d/20-jvb-udp-buffers.conf
    owner: root
    group: root
    mode: "0644"
    backup: yes
  notify:
    - systemctl apply