---
- name: reload nginx
  service: 
    name: nginx
    state: reloaded

- name: restart prosody
  service: 
    name: prosody
    state: restarted
- name: restart jicofo
  service: 
    name: jicofo
    state: restarted

- name: reload systemd
  command: systemctl daemon-reload