---
- name: check if ssh on defined port running
  wait_for:
    port: "{{ ssh_port }}"
    state: "started"
    host: "{{ inventory_hostname }}"
    connect_timeout: "5"
    timeout: "10"
  delegate_to: "localhost"
  ignore_errors: "yes"
  register: final_ssh

- name: change ssh port to {{ ansible_port }}
  include: changesshport.yml
  when: final_ssh is defined and final_ssh.failed == True

- name: generate /etc/ssh/sshd_config
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart sshd
