---
#- name: copy package(s) to host
#  copy:
#    src: files/{{ item }}
#    dest: "/opt/ansiblepackages/{{ item }}"
#    owner: root
#    group: root
#    mode: '0600'
#    backup: yes
#  with_items:
#    - check-mk-agent_2.0.0p17-1_all.deb

#- name: install package(s) on host
#  apt:
#    deb: "/opt/ansiblepackages/{{ item }}"
#  with_items:
#    - check-mk-agent_2.0.0p17-1_all.deb

- name: /etc/check_mk/fileinfo.cfg
  template:
    src: fileinfo.cfg.j2
    dest: /etc/check_mk/fileinfo.cfg
    owner: root
    group: root
    mode: "0644"
  when: "'nagios_agent' in group_names"

- name: create user monitoring
  command: adduser --gecos "" --disabled-password monitoring
  args:
    creates: /home/monitoring

- name: create folder /home/monitoring/.ssh
  file:
    path: /home/monitoring/.ssh
    state: directory
    owner: monitoring
    group: monitoring
    mode: '0750'

- name: generate /home/monitoring/.ssh/authorized_keys
  template:
    src: authorized_keys.j2
    dest: /home/monitoring/.ssh/authorized_keys
    owner: monitoring
    group: monitoring
    mode: "0750"

- name: Add ssh key for monitoring user
  lineinfile:
    path: /home/monitoring/.ssh/authorized_keys
    line: "{{ monitoring_user_public_key }}"
    backup: yes
  when: "'nagios_agent' in group_names"

- name: generate /etc/sudoers.d/monitoring
  template:
    src: sudoers_monitoring.j2
    dest: /etc/sudoers.d/monitoring
    owner: root
    group: root
    mode: "0600"

- name: disable check_mk-agent
  systemd:
    name: check_mk.socket
    state: stopped
    enabled: no
  when: "'nagios_agent' in group_names"
