---
- name: restart videobridge
  service: 
    name: jitsi-videobridge2
    state: restarted
- name: restart logrotate
  service: 
    name: logrotate
    state: restarted
- name: systemctl apply
  shell: sysctl --system
