---
- name: Set configured port fact
  set_fact:
    configured_port: "{{ ansible_port }}"

- name: Set inventory ansible_port to default
  set_fact:
    ansible_port: "22"

- name: Setup alternate SSH port
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^Port"
    line: "Port {{ configured_port }}"
  notify: "restart sshd"

- name: flush handlers to restart ssh
  meta: flush_handlers

- name: change port back to alternate SSH port
  set_fact:
    ansible_port: "{{ configured_port }}"
