---
- name: Install system tools and utilities
  apt:
    name: 
      - vlan
    update_cache: yes

- name: generate /etc/sysctl.d/30-disable-ipv6.conf (disable IPv6)
  template:
    src: 30-disable-ipv6.conf.j2
    dest: /etc/sysctl.d/30-disable-ipv6.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - systemctl apply

- name: generate /etc/network/interfaces.d/99_vlan_{{ privateVLANID }}.conf
  template:
    src: 99_vlan.conf.j2
    dest: /etc/network/interfaces.d/99_vlan_{{ privateVLANID }}.conf
    owner: root
    group: root
    mode: "0644"
  when: private_vlan_ip is defined
  register: vlan

- name: ifup vlan if vlan changed
  command: ifup {{ ansible_default_ipv4.interface }}.{{ privateVLANID }}
  when: vlan.changed