- name: set instanceVars for {{ instance }}
  set_fact:
    instanceVars: '{{ instancevars[instance] }}'
  when: instancevars[instance] is defined

- name: set usedWebVersion to match path
  set_fact:
    usedWebVersion: "jitsi-meet-{{ instanceVars.usedWebVersion }}"
  when: instanceVars.usedWebVersion is defined

- name: copy/update wwwroot-template for instance {{ instance }} from {{ usedWebVersion}}
  ansible.builtin.copy:
    src: "files/jitsi-www/base/{{ usedWebVersion}}/"
    dest: /var/www/jitsi-meet-{{ deployto | default(instance) }}
    local_follow: False
    owner: www-data
    group: www-data
    mode: '0755'
  when: redeploy is defined and usedWebVersion is defined

- name: copy wwwroot of instance {{ instance }}
  ansible.builtin.copy:
    src: files/jitsi-www/instances/{{ instance }}/wwwroot/
    dest: /var/www/jitsi-meet-{{ deployto | default(instance) }}
    local_follow: False
    owner: www-data
    group: www-data
    mode: '0755'
