---
- name: install cron-apt
  apt:
    name: 
      - cron-apt
    update_cache: yes
  when: "'no-cron-apt' not in group_names"

- name: generate /etc/cron-apt/action.d/3-download
  template:
    src: 3-download.j2
    dest: /etc/cron-apt/action.d/3-download
    owner: root
    group: root
    mode: "0644"
  when: "'no-cron-apt' not in group_names"
  notify:
    - restart cron
