---
- name: generate /etc/netplan/99_vlan.yaml
  template:
    src: 99_vlan.yaml.j2
    dest: /etc/netplan/99_vlan.yaml
    owner: root
    group: root
    mode: "0644"
  when: private_vlan_ip is defined
  notify:
    - netplan apply
