---
- name: install stuff
  apt:
    name:
      - apache2
      - php
#      - mariadb-server
      - libapache2-mod-php
      - npm
      - php-mbstring
      - php-xsl
      - php-dom
      - php-xml
      - php-gd
      - php-zip
      - php-sqlite3
      - php-intl
      - python3-pexpect

- name: create directory for acme-stuff /var/www/letsencrypt
  ansible.builtin.file:
    path: /var/www/letsencrypt
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: enable apache module rewrite
  command: a2enmod rewrite
  args:
    creates: /etc/apache2/mods-enabled/rewrite.load
  notify:
    reload apache2

- name: enable apache module headers
  command: a2enmod headers
  args:
    creates: /etc/apache2/mods-enabled/headers.load
  notify:
    reload apache2

- name: enable php module sqlite3
  command: phpenmd sqlite3
  args:
    creates: /etc/php/7.4/apache2/conf.d/20-sqlite3.ini
  notify:
    reload apache2

#ansible-playbook instances.yml --extra-vars "instance=instancename"
- name: configure jitsiadmin-instances
  include: include.yml jitsiadmin_instance={{ item }}
  loop: "{{ jitsiadmin_instances }}"
  when: jitsiadmin_instance is not defined or jitsiadmin_instance == item
