- name: Install Influxdb rep key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present
  when: "'telegraf' in group_names"

- name: Install Influxdb Repository
  apt_repository:
    repo: deb https://repos.influxdata.com/ubuntu focal stable
    state: present
    filename: influxdb
    update_cache: yes
  when: "'telegraf' in group_names"

- name: Install telegraf
  apt:
    name: 
      - telegraf
    update_cache: yes
  when: "'telegraf' in group_names"

- name: configure telegraf for all hosts
  blockinfile:
    path: /etc/telegraf/telegraf.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK --"
    block: |
      [[outputs.influxdb]]
        database = "{{ influxdb_database }}"
        urls = [ "{{ influxdb_url }}" ]
        username = "{{ influxdb_jitsi_user }}"
        password = "{{ influxdb_jitsi_password }}"
      [[inputs.net]]
      [[inputs.netstat]]
    backup: yes
  when: "'telegraf' in group_names"
  notify:
    - telegraf restart

- name: configure telegraf for group videobridge
  blockinfile:
    path: /etc/telegraf/telegraf.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK videobridge --"
    block: |
      [[inputs.http]]
        urls = [ "http://localhost:9000/colibri/stats" ]
        data_format = "json"
        name_override = "jitsi"
      [[inputs.http_response]]
        name_override = "jvb-health"
        urls = [
          "http://localhost:9000/about/health",
        ]
        response_timeout = "5s"
        method = "GET"
    backup: yes
  when: "'videobridge' in group_names and 'telegraf' in group_names"
  notify:
    - telegraf restart

- name: configure telegraf for group jitsisignal
  blockinfile:
    path: /etc/telegraf/telegraf.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK jitsisignal --"
    block: |
      [[inputs.http]]
        urls = [ "http://localhost:9002/stats" ]
        data_format = "json"
        name_override = "jicofo"
      [[inputs.http]]
        urls = [ "http://localhost:9001/status/format/json" ]
        data_format = "json"
        name_override = "nginx"
    backup: yes
  when: "'jitsisignal' in group_names and 'telegraf' in group_names"
  notify:
    - telegraf restart

- name: configure telegraf for group jigasi
  blockinfile:
    path: /etc/telegraf/telegraf.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK jigasi --"
    block: |
      [[inputs.http]]
        urls = [ "http://localhost:9001/about/stats" ]
        data_format = "json"
        name_override = "jigasi"
    backup: yes
  when: "'jigasi' in group_names and 'telegraf' in group_names"
  notify:
    - telegraf restart