- name: Install Influxdb rep key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present
  when: "'telegraf' in group_names"

- name: Install Influxdb Repository
  apt_repository:
    repo: deb https://repos.influxdata.com/ubuntu focal stable
    state: present
    filename: influxdb
    update_cache: yes
  when: "'telegraf' in group_names"

- name: Install telegraf
  apt:
    name: 
      - telegraf
    update_cache: yes
  when: "'telegraf' in group_names"

- name: generate /etc/telegraf/telegraf.conf
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
    backup: yes
  when: "'telegraf' in group_names"
  notify:
    - telegraf restart

- name: generate /etc/telegraf/telegraf.d/outputs.influxdb.conf
  template:
    src: outputs.influxdb.conf.j2
    dest: /etc/telegraf/telegraf.d/outputs.influxdb.conf
    backup: yes
  when: "'telegraf' in group_names"
  notify:
    - telegraf restart

- name: generate /etc/telegraf/telegraf.d/videobridge.conf
  template:
    src: videobridge.conf.j2
    dest: /etc/telegraf/telegraf.d/videobridge.conf
    backup: yes
  when: "'videobridge' in group_names and 'telegraf' in group_names"
  notify:
    - telegraf restart

- name: configure telegraf for group jitsisignal
  template:
    src: jitsisignal.conf.j2
    dest: /etc/telegraf/telegraf.d/jitsisignal.conf
    backup: yes
  when: "'jitsisignal' in group_names and 'telegraf' in group_names"
  notify:
    - telegraf restart

- name: configure telegraf for group jigasi
  template:
    src: jigasi.conf.j2
    dest: /etc/telegraf/telegraf.d/jigasi.conf
    backup: yes
  when: "'jigasi' in group_names and 'telegraf' in group_names"
  notify:
    - telegraf restart